# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="7472616365_plg"
version="${file.jarVersion}"
displayName="7472616365_plg"
credits="Classified"
authors="Classified"
description='''
Classified
'''
[[dependencies.trcplg]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trcplg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.18.2]"
    ordering="NONE"
    side="BOTH"
